2025-07-06 21:53:05,795 ERROR: Error 500: Error inesperado: Object of type Row is not JSON serializable | Details: {'timestamp': '2025-07-06T21:53:05.795069', 'error_code': 500, 'error_message': 'Error inesperado: Object of type Row is not JSON serializable', 'user_info': {'user_id': None, 'user_role': None, 'is_authenticated': False}, 'request_info': {'url': 'http://127.0.0.1:5000/lider', 'method': 'GET', 'ip_address': '127.0.0.1', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Sa'}} [in c:\Users\dj\Desktop\master\pr\error_handlers.py:41]
2025-07-06 21:53:18,983 ERROR: Error 500: Error inesperado: Object of type Row is not JSON serializable | Details: {'timestamp': '2025-07-06T21:53:18.983183', 'error_code': 500, 'error_message': 'Error inesperado: Object of type Row is not JSON serializable', 'user_info': {'user_id': None, 'user_role': None, 'is_authenticated': False}, 'request_info': {'url': 'http://127.0.0.1:5000/lider', 'method': 'GET', 'ip_address': '127.0.0.1', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Sa'}} [in c:\Users\dj\Desktop\master\pr\error_handlers.py:41]
2025-07-06 21:56:22,403 ERROR: Error 500: Error inesperado: Error binding parameter 1: type 'dict' is not supported | Details: {'timestamp': '2025-07-06T21:56:22.403538', 'error_code': 500, 'error_message': "Error inesperado: Error binding parameter 1: type 'dict' is not supported", 'user_info': {'user_id': None, 'user_role': None, 'is_authenticated': False}, 'request_info': {'url': 'http://127.0.0.1:5000/notificaciones', 'method': 'GET', 'ip_address': '127.0.0.1', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Sa'}} [in c:\Users\dj\Desktop\master\pr\error_handlers.py:41]
2025-07-06 21:56:23,299 ERROR: Error 500: Error inesperado: Error binding parameter 1: type 'dict' is not supported | Details: {'timestamp': '2025-07-06T21:56:23.298103', 'error_code': 500, 'error_message': "Error inesperado: Error binding parameter 1: type 'dict' is not supported", 'user_info': {'user_id': None, 'user_role': None, 'is_authenticated': False}, 'request_info': {'url': 'http://127.0.0.1:5000/notificaciones', 'method': 'GET', 'ip_address': '127.0.0.1', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Sa'}} [in c:\Users\dj\Desktop\master\pr\error_handlers.py:41]
2025-07-06 23:09:18,560 ERROR: Error 500: Error inesperado: no such table: usuarios | Details: {'timestamp': '2025-07-06T23:09:18.559845', 'error_code': 500, 'error_message': 'Error inesperado: no such table: usuarios', 'user_info': {'user_id': None, 'user_role': None, 'is_authenticated': False}, 'request_info': {'url': 'http://127.0.0.1:5000/descargar_informe', 'method': 'GET', 'ip_address': '127.0.0.1', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Sa'}} [in c:\Users\dj\Desktop\master\pr\error_handlers.py:41]
2025-07-06 23:09:40,401 ERROR: Error 500: Error inesperado: no such table: usuarios | Details: {'timestamp': '2025-07-06T23:09:40.400060', 'error_code': 500, 'error_message': 'Error inesperado: no such table: usuarios', 'user_info': {'user_id': None, 'user_role': None, 'is_authenticated': False}, 'request_info': {'url': 'http://127.0.0.1:5000/descargar_informe', 'method': 'GET', 'ip_address': '127.0.0.1', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Sa'}} [in c:\Users\dj\Desktop\master\pr\error_handlers.py:41]
2025-07-06 23:12:54,024 ERROR: Error 500: Error inesperado: expected str, bytes or os.PathLike object, not BytesIO | Details: {'timestamp': '2025-07-06T23:12:54.024057', 'error_code': 500, 'error_message': 'Error inesperado: expected str, bytes or os.PathLike object, not BytesIO', 'user_info': {'user_id': None, 'user_role': None, 'is_authenticated': False}, 'request_info': {'url': 'http://127.0.0.1:5000/descargar_informe', 'method': 'GET', 'ip_address': '127.0.0.1', 'user_agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/138.0.0.0 Sa'}} [in c:\Users\dj\Desktop\master\pr\error_handlers.py:41]
